/**
 * DDL project root detection, and expansion of its sources into a list of files.
 */

import { closeSync, existsSync, globSync, openSync, readSync, statSync } from "node:fs";
import { dirname, isAbsolute, join, resolve as resolvePath } from "node:path";

import { CONFIG_FILES, defaults, get, type Config, type Source, type SourceKind } from "../config/config.ts";

/**
 * Directories a known layout is made of, and what each one holds.
 *
 * These names are a **budget, not a definition**. Whatever they do not claim gets swept as `auto`
 * anyway — see `detectSources` — so a repo whose routines live under a name nobody here has heard
 * of is still catalogued in full, just at the cost of running both parsers over it. Recognising a
 * name buys the cheaper parse, and with it a judgment the sweep cannot make on its own: declaring
 * a directory as `routines` is saying *what gets defined in here is not schema*, which is what
 * keeps a procedure's backup copy of a table from competing with the real declaration.
 *
 * Two conventions are recognised, both from repos generated by `SHOW CREATE`: the Spanish one —
 * `tablas/` + `sp/` + `carga-valores/` — and the English one — `tables/` + `sps/`, `functions/`
 * or `procedures/` + `triggers/` + `seeds/`. A repo laid out either way needs no config file.
 *
 * `triggers/` is read as `tables`, which is not a typo: the DDL parser is what understands a
 * `CREATE TRIGGER`, since a trigger is catalogued together with the table it hangs off.
 *
 * What is deliberately **not** here is the English layout's `deploy_folder/`: those are migration
 * scripts, one per environment, and they carry `CREATE TABLE`s of tables already in `tables/`.
 * Cataloguing them would duplicate half the schema, which is the same reason `deploy.sql` is
 * excluded in the other layout. They are linted all the same — see `targets`.
 */
const LAYOUT: readonly { dir: string; kind: SourceKind }[] = [
  { dir: "tablas", kind: "tables" },
  { dir: "tables", kind: "tables" },
  { dir: "triggers", kind: "tables" },
  { dir: "sp", kind: "routines" },
  { dir: "sps", kind: "routines" },
  { dir: "functions", kind: "routines" },
  { dir: "procedures", kind: "routines" },
  { dir: "carga-valores", kind: "data" },
  { dir: "seeds", kind: "data" },
];

/**
 * Layouts recognisable enough to declare a project without reading a single file.
 *
 * A shortcut and not the definition: `isDdlProject` falls through to reading the files when none
 * of these matches, so a layout missing from this list costs a directory walk and never a wrong
 * answer.
 *
 * `tablas/` and `sp/` are each enough on their own: nothing else is called that. `tables/`,
 * `sps/`, `functions/` and `procedures/` are all plausible directories in a repo that has nothing
 * to do with a database, so those are only taken in pairs.
 */
export const DECLARES_PROJECT: readonly (readonly string[])[] = [
  ["tablas"],
  ["sp"],
  ["tables", "sps"],
  ["tables", "functions"],
  ["tables", "procedures"],
];

/** Directories whose files are linted but never catalogued. */
const TARGET_ONLY_DIRS = ["deploy_folder"];

/**
 * Directories nothing automatic ever walks into.
 *
 * Not schema by anybody's convention — a vendored `.sql` fixture is not a declaration — and
 * skipping them is also what keeps a sweep cheap enough to run while an editor waits on it.
 *
 * Only what sqldex works out **by itself** is filtered this way. Sources written by hand in
 * `.sqldex.json` are honoured exactly as written: naming a directory there is the declaration.
 */
const NEVER_SWEPT: readonly string[] = ["node_modules", ".git", "dist", "vendor"];

/**
 * A `globSync` `exclude`, which **prunes** rather than filters: answering `true` for a directory
 * costs its whole subtree nothing. That is the difference between a sweep an editor can afford and
 * one it cannot.
 */
function pruning(dirs: readonly string[]): (relative: string) => boolean {
  return (relative) => relative.split(/[/\\]/).some((segment) => dirs.includes(segment));
}

/**
 * What a swept **source** skips, on top of the above: `deploy_folder/` is half a duplicated schema
 * and belongs to the lint targets, so a sweep that picks up whatever the layout left behind must
 * not smuggle it back into the catalog.
 */
const pruneSources = pruning([...TARGET_ONLY_DIRS, ...NEVER_SWEPT]);

function isDirectory(path: string): boolean {
  try {
    return statSync(path).isDirectory();
  } catch {
    return false;
  }
}

/**
 * Root of the project containing `start`, by marker.
 *
 * Markers are tried in priority order, each one all the way up the tree before the next, so a
 * distant config file beats a nearby `.git`: if somebody took the trouble to write it, that is
 * the root they meant.
 */
export function findRoot(start: string, options?: Partial<Config>): string | undefined {
  const markers = options?.root_markers ?? defaults.root_markers;
  const from = isDirectory(start) ? resolvePath(start) : dirname(resolvePath(start));

  for (const marker of markers) {
    let dir = from;
    for (;;) {
      if (existsSync(join(dir, marker))) return dir;
      const parent = dirname(dir);
      if (parent === dir) break;
      dir = parent;
    }
  }
  return undefined;
}

/**
 * Default layout when the repo carries no config file.
 *
 * The recognised directories come first, for their `kind`; then the whole tree is swept as `auto`
 * to pick up whatever they left behind. The `kind` is a budget, never a filter — `auto` runs both
 * parsers, so a swept file gives up exactly what a typed one would.
 *
 * The sweep runs **even when a layout matched**, and that is the point. A *partial* match was the
 * worst of the three cases: a repo holding `tables/` and `triggers/`, with its routines under a
 * name not listed above, matched the layout, stopped looking, and produced a catalog silently
 * missing every routine — while a repo matching nothing at all fell through to the sweep and came
 * out right. Recognising half a convention should not cost more than recognising none of it.
 *
 * `expand` keeps the `kind` of the first source that catches a file and the typed sources are
 * declared first, so the sweep can only ever add. That is the property `tools/check-flat.ts`
 * exists to hold down.
 */
export function detectSources(root: string): Source[] {
  const sources: Source[] = [];
  for (const entry of LAYOUT) {
    if (isDirectory(join(root, entry.dir))) sources.push({ glob: `${entry.dir}/*.sql`, kind: entry.kind });
  }

  sources.push({ glob: "**/*.sql", kind: "auto" });
  return sources;
}

/**
 * Default set of files to lint: everything the catalog is built from, plus the migration
 * directories, which contribute no definitions but are code that runs.
 */
export function detectTargets(root: string, sources: readonly Source[]): Source[] {
  const targets = [...sources];
  for (const dir of TARGET_ONLY_DIRS) {
    if (isDirectory(join(root, dir))) targets.push({ glob: `${dir}/**/*.sql`, kind: "auto" });
  }
  return targets;
}

/**
 * Does a file declare something a catalog would hold?
 *
 * Cheap and deliberately looser than a parse, in the same spirit as `catalog.ts`'s
 * `mightHoldTable`: this only decides whether to *start*. Wrong towards yes costs a server that
 * starts, finds nothing, and says so in its log. Wrong towards no is a schema project that never
 * produces a diagnostic and never explains why — so the bias is deliberate.
 *
 * The two words are allowed to sit apart because `SHOW CREATE` puts clauses between them:
 * `CREATE DEFINER=` before every routine and every trigger, `ALGORITHM=` and `SQL SECURITY`
 * before a view. Not across a `;`, so a match stays inside one statement.
 */
const DECLARES_DDL = /\bcreate\b[^;]{0,120}?\b(?:table|procedure|function|trigger|view|event)\b/i;

/** How much of a file the scan reads, and how many files it is willing to read at all. */
const SCAN_HEAD_BYTES = 64 * 1024;
const SCAN_FILE_LIMIT = 200;

/**
 * The first `SCAN_HEAD_BYTES` of a file.
 *
 * A `CREATE` is near the top of a file or it is not in it, and reading the head is what keeps a
 * large seed file from being read in full to answer "no".
 */
function head(path: string): string {
  const fd = openSync(path, "r");
  try {
    const buffer = Buffer.allocUnsafe(SCAN_HEAD_BYTES);
    return buffer.toString("utf8", 0, readSync(fd, buffer, 0, SCAN_HEAD_BYTES, 0));
  } finally {
    closeSync(fd);
  }
}

/**
 * Does anything under this root create a table, a routine or a trigger?
 *
 * Bounded on every axis, because an editor is waiting on the answer: the walk prunes the
 * directories no schema lives in, each file is read only at its head, and the whole thing gives up
 * after `SCAN_FILE_LIMIT` files. A repo whose first two hundred `.sql` files declare nothing is
 * not a schema project, and a bound that can be wrong in that direction is worth more than one
 * that can hang an editor.
 *
 * It runs once, when a server starts, so there is nothing here worth memoising.
 */
function holdsDdl(root: string): boolean {
  let read = 0;
  for (const relative of globSync("**/*.sql", { cwd: root, exclude: pruneSources })) {
    if (++read > SCAN_FILE_LIMIT) return false;
    try {
      if (DECLARES_DDL.test(head(join(root, relative)))) return true;
    } catch {
      // Unreadable is not an answer either way. The next file may be one.
    }
  }
  return false;
}

/**
 * Is this directory a DDL project, or just a repo that happens to contain a `.sql`?
 *
 * The difference matters because `.git` is among the root markers: without this filter, an editor
 * would start up in any repo with a stray `.sql` and set about indexing `**\/*.sql` with nobody
 * asking. As in DataGrip, the project is declared — but *declared* is not the same as *named*. A
 * config file declares it; a recognised layout declares it; and so does the one thing true of
 * every schema repo and of no other, which is a `.sql` file that creates something.
 *
 * The three tests are in that order because that is their cost. The first two are `stat` calls.
 * The third walks the tree and reads files, and only a repo the first two could not answer for
 * ever reaches it — which is exactly the repo that used to get silence, since a layout under a
 * name nobody listed is not a repo with a stray `.sql` in it.
 *
 * **The CLI does not apply this guard.** It is a guard about implicit activation, and running
 * `sqldex check .` is not implicit: the invocation *is* the declaration of intent, so a flat
 * directory with no recognised layout has to work.
 */
export function isDdlProject(root: string): boolean {
  if (CONFIG_FILES.some((name) => existsSync(join(root, name)))) return true;
  if (DECLARES_PROJECT.some((combination) => combination.every((dir) => isDirectory(join(root, dir))))) return true;

  return holdsDdl(root);
}

/** Root of the DDL project containing a path, or `undefined` if there is none. */
export function resolveProject(path: string, options?: Partial<Config>): string | undefined {
  const root = findRoot(path, options);
  return root && isDdlProject(root) ? root : undefined;
}

/** Absolute paths excluded by the `exclude` patterns. */
function excludedPaths(root: string, patterns: readonly string[]): Set<string> {
  const set = new Set<string>();
  for (const pattern of patterns) {
    for (const path of globSync(pattern, { cwd: root })) set.add(join(root, path));
  }
  return set;
}

export interface FileRef {
  /** Absolute path. */
  path: string;
  kind: SourceKind;
}

/**
 * Expands a list of sources into the files they name.
 *
 * A file matching several sources keeps the `kind` of the first that caught it: specific sources
 * are declared before catch-alls, so `tablas/*.sql` beats a `**\/*.sql` placed later. Each glob's
 * results are sorted, because `globSync` does not promise an order and a catalog whose duplicate
 * report depends on directory-entry order is not reproducible.
 *
 * `prune` is only ever passed for sources sqldex worked out by itself — see `NEVER_SWEPT`.
 */
function expand(
  root: string,
  sources: readonly Source[],
  skip: ReadonlySet<string>,
  prune?: (relative: string) => boolean,
): FileRef[] {
  const files: FileRef[] = [];
  const seen = new Set<string>();
  for (const source of sources) {
    const matched = globSync(source.glob, { cwd: root, exclude: prune }).sort();
    for (const relative of matched) {
      const path = isAbsolute(relative) ? relative : join(root, relative);
      if (seen.has(path) || skip.has(path) || isDirectory(path)) continue;
      seen.add(path);
      files.push({ path, kind: source.kind ?? "auto" });
    }
  }
  return files;
}

/** Every file the project's catalog is built from. */
export function sourceFiles(root: string, options?: Partial<Config>): FileRef[] {
  const config = get(root, options);
  const sources = config.sources ?? detectSources(root);
  const prune = config.sources ? undefined : pruneSources;
  return expand(root, sources, excludedPaths(root, config.exclude), prune);
}

/**
 * Every file the project lints.
 *
 * A superset of `sourceFiles` by default. The two are the same list in an editor, where you lint
 * what you index, and different in CI, where the migration scripts have to be checked against a
 * catalog they must not be part of.
 */
export function targetFiles(root: string, options?: Partial<Config>): FileRef[] {
  const config = get(root, options);
  const sources = config.sources ?? detectSources(root);
  const targets = config.targets ?? detectTargets(root, sources);
  // `deploy_folder/` is skipped as a source and wanted as a target, so the sweep prunes less here.
  // Either list written by hand makes the whole set hand-written, and nothing hand-written is pruned.
  const prune = config.sources || config.targets ? undefined : pruning(NEVER_SWEPT);
  return expand(root, targets, excludedPaths(root, config.exclude), prune);
}
