/**
 * DDL project root detection, and expansion of its sources into a list of files.
 */

import { existsSync, globSync, statSync } from "node:fs";
import { dirname, isAbsolute, join, resolve as resolvePath } from "node:path";

import { CONFIG_FILES, defaults, get, type Config, type Source, type SourceKind } from "../config/config.ts";

/**
 * Directories a known layout is made of, and what each one holds.
 *
 * Two conventions are recognised, both from repos generated by `SHOW CREATE`: the Spanish one —
 * `tablas/` + `sp/` + `carga-valores/` — and the English one — `tables/` + `sps/` + `functions/`
 * + `triggers/`. A repo laid out either way needs no config file.
 *
 * `triggers/` is read as `tables`, which is not a typo: the DDL parser is what understands a
 * `CREATE TRIGGER`, since a trigger is catalogued together with the table it hangs off.
 *
 * What is deliberately **not** here is the English layout's `deploy_folder/`: those are migration
 * scripts, one per environment, and they carry `CREATE TABLE`s of tables already in `tables/`.
 * Cataloguing them would duplicate half the schema, which is the same reason `deploy.sql` is
 * excluded in the other layout. They are linted all the same — see `targets`.
 */
const LAYOUT: readonly { dir: string; kind: SourceKind }[] = [
  { dir: "tablas", kind: "tables" },
  { dir: "tables", kind: "tables" },
  { dir: "triggers", kind: "tables" },
  { dir: "sp", kind: "routines" },
  { dir: "sps", kind: "routines" },
  { dir: "functions", kind: "routines" },
  { dir: "carga-valores", kind: "data" },
];

/**
 * What declares a DDL project, rather than a repo that happens to have a `.sql` in it.
 *
 * `tablas/` and `sp/` are each enough on their own: nothing else is called that. `tables/`, on
 * the other hand, is a plausible directory in a repo that has nothing to do with a database, so
 * the English layout is only recognised when a routines directory is there too.
 */
const DECLARES_PROJECT: readonly (readonly string[])[] = [
  ["tablas"],
  ["sp"],
  ["tables", "sps"],
  ["tables", "functions"],
];

/** Directories whose files are linted but never catalogued. */
const TARGET_ONLY_DIRS = ["deploy_folder"];

function isDirectory(path: string): boolean {
  try {
    return statSync(path).isDirectory();
  } catch {
    return false;
  }
}

/**
 * Root of the project containing `start`, by marker.
 *
 * Markers are tried in priority order, each one all the way up the tree before the next, so a
 * distant config file beats a nearby `.git`: if somebody took the trouble to write it, that is
 * the root they meant.
 */
export function findRoot(start: string, options?: Partial<Config>): string | undefined {
  const markers = options?.root_markers ?? defaults.root_markers;
  const from = isDirectory(start) ? resolvePath(start) : dirname(resolvePath(start));

  for (const marker of markers) {
    let dir = from;
    for (;;) {
      if (existsSync(join(dir, marker))) return dir;
      const parent = dirname(dir);
      if (parent === dir) break;
      dir = parent;
    }
  }
  return undefined;
}

/**
 * Default layout when the repo carries no config file.
 *
 * If none of the known directories shows up, the whole tree is swept and the parser decides what
 * each file is — slower, but sqldex still works in a repo with another convention. The `kind` is
 * a budget, never a filter: `auto` runs both parsers, so a flat sweep finds exactly what a typed
 * layout finds.
 */
export function detectSources(root: string): Source[] {
  const sources: Source[] = [];
  for (const entry of LAYOUT) {
    if (isDirectory(join(root, entry.dir))) sources.push({ glob: `${entry.dir}/*.sql`, kind: entry.kind });
  }

  if (sources.length === 0) sources.push({ glob: "**/*.sql", kind: "auto" });
  return sources;
}

/**
 * Default set of files to lint: everything the catalog is built from, plus the migration
 * directories, which contribute no definitions but are code that runs.
 */
export function detectTargets(root: string, sources: readonly Source[]): Source[] {
  const targets = [...sources];
  for (const dir of TARGET_ONLY_DIRS) {
    if (isDirectory(join(root, dir))) targets.push({ glob: `${dir}/**/*.sql`, kind: "auto" });
  }
  return targets;
}

/**
 * Is this directory a DDL project, or just a repo that happens to contain a `.sql`?
 *
 * The difference matters because `.git` is among the root markers: without this filter, an editor
 * would start up in any repo with a stray `.sql` and set about indexing `**\/*.sql` with nobody
 * asking. As in DataGrip, the project is declared: either there is a config file, or the layout
 * is recognised on its own.
 *
 * **The CLI does not apply this guard.** It is a guard about implicit activation, and running
 * `sqldex check .` is not implicit: the invocation *is* the declaration of intent, so a flat
 * directory with no recognised layout has to work.
 */
export function isDdlProject(root: string): boolean {
  if (CONFIG_FILES.some((name) => existsSync(join(root, name)))) return true;

  return DECLARES_PROJECT.some((combination) => combination.every((dir) => isDirectory(join(root, dir))));
}

/** Root of the DDL project containing a path, or `undefined` if there is none. */
export function resolveProject(path: string, options?: Partial<Config>): string | undefined {
  const root = findRoot(path, options);
  return root && isDdlProject(root) ? root : undefined;
}

/** Absolute paths excluded by the `exclude` patterns. */
function excludedPaths(root: string, patterns: readonly string[]): Set<string> {
  const set = new Set<string>();
  for (const pattern of patterns) {
    for (const path of globSync(pattern, { cwd: root })) set.add(join(root, path));
  }
  return set;
}

export interface FileRef {
  /** Absolute path. */
  path: string;
  kind: SourceKind;
}

/**
 * Expands a list of sources into the files they name.
 *
 * A file matching several sources keeps the `kind` of the first that caught it: specific sources
 * are declared before catch-alls, so `tablas/*.sql` beats a `**\/*.sql` placed later. Each glob's
 * results are sorted, because `globSync` does not promise an order and a catalog whose duplicate
 * report depends on directory-entry order is not reproducible.
 */
function expand(root: string, sources: readonly Source[], skip: ReadonlySet<string>): FileRef[] {
  const files: FileRef[] = [];
  const seen = new Set<string>();
  for (const source of sources) {
    const matched = globSync(source.glob, { cwd: root }).sort();
    for (const relative of matched) {
      const path = isAbsolute(relative) ? relative : join(root, relative);
      if (seen.has(path) || skip.has(path) || isDirectory(path)) continue;
      seen.add(path);
      files.push({ path, kind: source.kind ?? "auto" });
    }
  }
  return files;
}

/** Every file the project's catalog is built from. */
export function sourceFiles(root: string, options?: Partial<Config>): FileRef[] {
  const config = get(root, options);
  const sources = config.sources ?? detectSources(root);
  return expand(root, sources, excludedPaths(root, config.exclude));
}

/**
 * Every file the project lints.
 *
 * A superset of `sourceFiles` by default. The two are the same list in an editor, where you lint
 * what you index, and different in CI, where the migration scripts have to be checked against a
 * catalog they must not be part of.
 */
export function targetFiles(root: string, options?: Partial<Config>): FileRef[] {
  const config = get(root, options);
  const sources = config.sources ?? detectSources(root);
  const targets = config.targets ?? detectTargets(root, sources);
  return expand(root, targets, excludedPaths(root, config.exclude));
}
