/**
 * MySQL language words, so an identifier naming a column can be told apart from one that is
 * syntax.
 *
 * Only the diagnostics use it, when checking unqualified columns — the one place where a
 * decision has to be made about a **bare** identifier. Everywhere else the context already says
 * what is being looked at. It does not try to be MySQL's full list — that is around 700 words —
 * but to cover what shows up in hand-written SQL, which is what gets checked.
 */

const WORDS = `
ACCESSIBLE ACTION ADD AFTER AGAINST ALGORITHM ALL ALTER ALWAYS ANALYZE AND ANY AS ASC ASCII
ASENSITIVE AUTO_INCREMENT AVG AVG_ROW_LENGTH BEFORE BEGIN BETWEEN BIGINT BINARY BIT BLOB BOOL
BOOLEAN BOTH BTREE BY CALL CASCADE CASE CAST CHAIN CHANGE CHAR CHARACTER CHARSET CHECK CHECKSUM
CLOSE COALESCE COLLATE COLLATION COLUMN COLUMNS COMMENT COMMIT COMMITTED COMPACT COMPLETION
COMPRESSED CONCAT CONCAT_WS CONDITION CONNECTION CONSISTENT CONSTRAINT CONTAINS CONTINUE CONVERT
COUNT CREATE CROSS CUME_DIST CURDATE CURRENT CURRENT_DATE CURRENT_TIME CURRENT_TIMESTAMP
CURRENT_USER CURSOR CURTIME DATA DATABASE DATE DATEDIFF DATETIME DATE_ADD DATE_FORMAT DATE_SUB
DAY DAYNAME DAYOFMONTH DAYOFWEEK DAYOFYEAR DEALLOCATE DEC DECIMAL DECLARE DEFAULT DEFINER
DELAYED DELETE DELIMITER DENSE_RANK DESC DESCRIBE DETERMINISTIC DISTINCT DISTINCTROW DIV DO
DOUBLE DROP DUAL DUPLICATE EACH ELSE ELSEIF ENCLOSED END ENGINE ENUM ESCAPE ESCAPED EVENT EXCEPT
EXECUTE EXISTS EXIT EXPLAIN EXTRACT FALSE FETCH FIELD FIRST FIRST_VALUE FIXED FLOAT FLOOR FLUSH
FOLLOWING FOR FORCE FOREIGN FORMAT FOUND FROM FULL FULLTEXT FUNCTION GENERATED GET GET_LOCK
GLOBAL GRANT GREATEST GROUP GROUP_CONCAT HANDLER HASH HAVING HELP HIGH_PRIORITY HOUR IDENTIFIED
IF IFNULL IGNORE IN INDEX INFILE INNER INOUT INSENSITIVE INSERT INSTR INT INT1 INT2 INT3 INT4
INT8 INTEGER INTERVAL INTO INVOKER IS ISOLATION ITERATE JOIN JSON JSON_ARRAY JSON_ARRAYAGG
JSON_CONTAINS JSON_EXTRACT JSON_KEYS JSON_LENGTH JSON_MERGE_PATCH JSON_OBJECT JSON_OBJECTAGG
JSON_QUOTE JSON_REMOVE JSON_REPLACE JSON_SEARCH JSON_SET JSON_TABLE JSON_TYPE JSON_UNQUOTE
JSON_VALID KEY KEYS KILL LAG LANGUAGE LAST LAST_DAY LAST_INSERT_ID LAST_VALUE LEAD LEADING
LEAST LEAVE LEFT LENGTH LEVEL LIKE LIMIT LINEAR LINES LOAD LOCAL LOCALTIME LOCALTIMESTAMP LOCATE
LOCK LOGS LONG LONGBLOB LONGTEXT LOOP LOWER LOW_PRIORITY LPAD LTRIM MAKEDATE MASTER MATCH MAX
MAXVALUE MEDIUMBLOB MEDIUMINT MEDIUMTEXT MEMORY MERGE MICROSECOND MID MIDDLEINT MIN MINUTE MOD
MODE MODIFIES MODIFY MONTH MONTHNAME NAME NAMES NATURAL NEW NEXT NO NOT NOW NO_WRITE_TO_BINLOG
NTH_VALUE NTILE NULL NULLIF NUMERIC OF OFFSET OJ OLD ON ONLY OPEN OPTIMIZE OPTION OPTIONALLY OR
ORDER OUT OUTER OUTFILE OVER PARTITION PASSWORD PERCENT_RANK PERIOD PRECEDING PRECISION PREPARE
PRIMARY PRIVILEGES PROCEDURE PROCESSLIST PURGE QUARTER QUERY QUICK QUOTE RANGE RANK READ READS
REAL RECURSIVE REFERENCES REGEXP RELEASE RENAME REPEAT REPEATABLE REPLACE REQUIRE RESIGNAL
RESTRICT RETURN RETURNED_SQLSTATE RETURNS REVERSE REVOKE RIGHT RLIKE ROLLBACK ROUND ROUTINE ROW
ROWS ROW_COUNT ROW_FORMAT ROW_NUMBER RPAD RTRIM SAVEPOINT SCHEMA SECOND SECURITY SELECT SENSITIVE
SEPARATOR SERIALIZABLE SESSION SET SHARE SHOW SIGNAL SIGNED SIMPLE SMALLINT SNAPSHOT SOME SPATIAL
SPECIFIC SQL SQLEXCEPTION SQLSTATE SQLWARNING SQL_BIG_RESULT SQL_CALC_FOUND_ROWS SQL_SMALL_RESULT
SSL START STARTING STATUS STDDEV STORAGE STORED STRAIGHT_JOIN STR_TO_DATE SUBDATE SUBSTR SUBSTRING
SUBSTRING_INDEX SUM TABLE TABLES TEMPORARY TERMINATED TEXT THEN TIME TIMEDIFF TIMESTAMP
TIMESTAMPADD TIMESTAMPDIFF TINYBLOB TINYINT TINYTEXT TO TRAILING TRANSACTION TRIGGER TRIM TRUE
TRUNCATE TYPE UNBOUNDED UNCOMMITTED UNDO UNION UNIQUE UNIX_TIMESTAMP UNLOCK UNSIGNED UNTIL UPDATE
UPPER USAGE USE USER USING UTC_DATE UTC_TIME UTC_TIMESTAMP VALUE VALUES VARBINARY VARCHAR
VARCHARACTER VARIABLES VARYING VIEW VIRTUAL WEEK WEEKDAY WEEKOFYEAR WHEN WHERE WHILE WINDOW WITH
WORK WRITE XOR YEAR YEARWEEK ZEROFILL

DIAGNOSTICS NUMBER MESSAGE_TEXT MYSQL_ERRNO CLASS_ORIGIN SUBCLASS_ORIGIN CONSTRAINT_CATALOG
CONSTRAINT_SCHEMA CONSTRAINT_NAME CATALOG_NAME SCHEMA_NAME TABLE_NAME COLUMN_NAME CURSOR_NAME
`;

/** Reserved words, types and functions. Members are UPPER CASE. */
export const KEYWORDS: ReadonlySet<string> = new Set(WORDS.split(/\s+/).filter(Boolean));

/** Is the word MySQL syntax rather than a name? */
export function isKeyword(word: string): boolean {
  return KEYWORDS.has(word.toUpperCase());
}
